config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :search_queries

  namespace :api do
    namespace :v1 do
      devise_for :users
      resources :search_queries, only: [:show, :create] do
        resources :keyword_search_results, only: [:show]
      end
    end
  end

  get "search_queries/:search_query_id/keyword_search_results/:id", to: "api/v1/keyword_search_results#show", as: "keyword_search_result"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/keyword_search_result.rb
class KeywordSearchResult < ApplicationRecord
  validates :query, presence: true
  belongs_to :search_query
  after_create :scrap_data

  private

  def scrap_data
    data = Scraper::GoogleScraperService.new(keyword: self.query).call
    self.update!(data)
  end
end

app/models/search_query.rb
require 'csv'

class SearchQuery < ApplicationRecord
  belongs_to :user
  has_many :keyword_search_results, dependent: :destroy
  validates :keywords, presence: true
  after_commit :create_keyword_search_results, on: :create

  def self.import(file, user)
    keywords = []
    CSV.foreach(file.path) do |row|
      if row.count > 1
        row.each do |keyword|
          keywords << keyword
        end
      else
        keywords << row[0]
      end
    end

    return if keywords.count > 100

    search_query = SearchQuery.new(user_id: user.id)
    search_query.keywords = keywords
    search_query.save
  end

  private

  def create_keyword_search_results
    self.keywords.each do |keyword|
      KeywordSearchResult.create!(search_query: self, query: keyword)
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :search_queries
end

app/controllers/api/v1/keyword_search_results_controller.rb
module Api
  module V1
    class KeywordSearchResultsController < ApplicationController
      before_action :authenticate_user!

      def show
        query = SearchQuery.find_by(id: params[:search_query_id])
        keyword = query.keyword_search_results.find_by(id: params[:id])
        response = {
          query:keyword.query,
          advertisors_count:keyword.advertisors_count,
          links_count:keyword.links_count,
          results_count:keyword.results_count,
          code:keyword.code,
        }
        respond_to do |format|
          format.json { render json: {keyword_search_result:response, status: "OK"} }
          format.html { @keyword_search_result = keyword }
        end
      end
    end
  end
end

app/controllers/api/v1/search_queries_controller.rb
module Api
  module V1
    class SearchQueriesController < ApplicationController
      protect_from_forgery with: :null_session
      before_action :authenticate_user!

      def create
        user = User.find_by(id: params[:user_id])
      	SearchQuery.import(params[:file], user)
        respond_to do |format|
          format.json { render json: {status: "OK"} }
        end
      end

      def show
        search_query = SearchQuery.find_by(id: params[:id])
        respond_to do |format|
          format.json { render json: {keywords:search_query.keywords, status: "OK"} }
        end
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/search_queries_controller.rb
class SearchQueriesController < ApplicationController
  before_action :set_query, :only => [:show, :destroy]
  before_action :authenticate_user!

  def new
  	@search_query = SearchQuery.new
  end

  def create
    unless SearchQuery.import(params[:search_query][:file], current_user)
      flash[:warning] = 'Please enter less than 100 keywords.'
    end
    redirect_to root_path
  end

  def index
  	@queries = current_user.search_queries
  end

  def show
  	@keywords = @query.keyword_search_results
  end

  def destroy
  	if @query.destroy
  	  redirect_to search_queries_path
  	end
  end

  private

  def set_query
  	@query = SearchQuery.find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_queries_helper.rb
module SearchQueriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NimbleTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  </head>

  <body>
    <%= render "shared/nav_bar" %>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<section class="mt-5">
  <div class="mask d-flex align-items-center h-100 gradient-custom-3">
    <div class="container h-100">
      <h2 class="text-uppercase mb-3">Nimble Test App</h2>
      <% if user_signed_in? %>
      	<%= link_to "Search", new_search_query_path %><br />
      	<%= link_to "Previous Searches", search_queries_path %>
      <% end %>
    </div>
  </div>
</section>

app/views/search_queries/index.html.erb
<section class="mt-5">
  <div class="mask d-flex align-items-center h-100 gradient-custom-3">
    <div class="container h-100">
      <h2 class="text-uppercase mb-3">Previous Searches</h2>
      <table class="table table-hover">
        <thead>
          <tr>
            <th scope="col">id</th>
            <th scope="col">Date</th>
            <th scope="col"># of Keywords</th>
            <th scope="col">First Keyword</th>
          </tr>
        </thead>
        <tbody class="table-group-divider table-divider-color">
          <% @queries.each do |query| %>
            <tr>
              <td><%= query.id %></td>
              <td><%= link_to query.created_at, search_query_path(query)%></td>
              <td><%= query.keywords.count %></td>
              <td><%= query.keywords[0] %></td>
              <td><%= link_to "Delete", search_query_path(query), data: { "turbo-method": :delete, confirm: "Are you sure?", turbo_confirm: "Are you sure?" }, method: :delete %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</section>

app/views/search_queries/new.html.erb
<section class="mt-5">
  <div class="mask d-flex align-items-center h-100 gradient-custom-3">
    <div class="container h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-9 col-lg-7 col-xl-6">
          <div class="card" style="border-radius: 15px;">
            <div class="card-body p-5">
              <h2 class="text-uppercase text-center mb-5">Search</h2>

              <%= form_for @search_query, url: search_queries_path do |f| %>
                <div class="row align-items-center py-3">
                  <div class="col-md-3 ps-5">
                    <h6 class="mb-0">Upload CV</h6>
                  </div>
                  <div class="col-md-9 pe-5">
                    <label class="btn btn-primary">
                      Choose a file
                      <span style="display:none;">
                        <%= f.file_field :file, required: true %>
                      </span>
                    </label>
                  </div>
                </div>
                <div class="small text-muted mt-2">
                  Upload a CSV file containing keywords.
                </div>


                <div class="d-flex justify-content-center">
                  <%= f.submit "Search", class: "mt-3 btn btn-primary btn-block btn-lg" %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/search_queries/show.html.erb
<section class="mt-5">
  <div class="mask d-flex align-items-center h-100 gradient-custom-3">
    <div class="container h-100">
      <h2 class="text-uppercase mb-3">Previous Searches</h2>
      <table class="table table-hover">
        <thead>
          <tr>
            <th scope="col">Keyword</th>
            <th scope="col">Advertisors count</th>
            <th scope="col">Links Count</th>
            <th scope="col">Results count</th>
          </tr>
        </thead>
        <tbody class="table-group-divider table-divider-color">
          <% @keywords.each do |keyword| %>
              <tr>
                <td>
                  <%= link_to keyword.query, keyword_search_result_path(keyword.search_query, keyword)%>
                </td>
                <td><%= keyword.advertisors_count %></td>
                <td><%= keyword.links_count %></td>
                <td><%= keyword.results_count %></td>
              </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</section>

app/views/shared/_nav_bar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <span class="navbar-brand">Nimble Test</span>

    <div class="navbar flex-grow-1" id="navbarButtonsExample">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 mr-auto">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
      </ul>

      <div class="d-flex align-items-center ml-auto">
        <% if user_signed_in? %>
          <%= link_to "Sign Out", destroy_user_session_path, class: "btn btn-link px-3 me-2", data: { "turbo-method": :delete }  %>
        <% else %>
          <%= link_to "Login", new_user_session_path, class: "btn btn-link px-3 me-2" %>
          <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary me-3" %>
        <% end %>
      </div>
    </div>
  </div>
</nav>